include(
    ":app",
    ":libraries:remote",
    ":libraries:domain",
    ":libraries:data",
    ":core",
    ":features:recipes:recipe",
    ":presentation",
    ":features:recipes:model",
    ":common:views",
    ":features:recipes:recipeDetail",
    ":features:recipes:stepDetail",
    ":features:videoPlayer",
    ":common:common-test"
)
